### ISSUE TITLE
Packet injection and receiving raw wifi

### ISSUE THREAD

**Issue by ernacktob** [cnlohr/esp8266rawpackets#1]
Hi, this is not really an "issue", but I just saw your work on trying to get the ESP8266 to do some raw ieee82011 packet processing. As it turns out, I've been working on this for some time as well. It would be interesting for all those who have this same goal to keep in touch and show updates on their progress.

**Comment by cnlohr** [comment]
Indeed.  I really wish I could get 802.11 association /and/ raw packet access so I could do my own broadcast network.  Though ESP now is starting with the ESP NOW thing, I don't really like how complicated it is.

**Comment by ernacktob** [comment]
When you say raw packet access, does it include packets sent to MAC addresses other than your (own / broadcast)? I've found a way to get access to the broadcast raw packets, so this might be useful perhaps. Combined with the ppTxPkt / ieee80211_output_pbuf (for link layer frames), this could be a nice starting point for such a network.

**Comment by cnlohr** [comment]
Sorry about that.  It is just the raw bytes in wireshark. So, it's certainly containing the preamble, etc... But that's about it.  It just uses the ppTxPkt thing.

**Comment by evanou** [comment]
Charles, I am looking into working on a ESP based beacon, will be similar to BLE tag, I will include some sensor info before broadcast, your example provided some starting point for my project, and I will update my progress here as well.  Thanks.

**Comment by cnlohr** [comment]
Excellent.  I am still searching for some way to be connected using wifi and simultaneously communicate to the underlying packets.

Interestingly, there is this whole talk of the ESP NOW thing and I hope to see what comes of it.

**Comment by cnlohr** [comment]
Answer was not much.  BTW - closing issue due to age.
