### ISSUE TITLE
image.elf section `.text' will not fit in region `iram1_0_seg' region `iram1_0_seg' overflowed by 224 bytes

### ISSUE THREAD

**Issue by sarwadenj** [cnlohr/esp8266rawpackets#3]
HI,
I'm using ESP12-E when i tried to    "make burn" cmd i'm getting following error: 

/home/esp8266/vishal/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: image.elf section `.text' will not fit in region `iram1_0_seg'
/home/esp8266/vishal/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: region `iram1_0_seg' overflowed by 224 bytes
collect2: error: ld returned 1 exit status

so how i fix this issue?

Thanks

**Comment by cnlohr** [comment]
You're gonna have to use 1.5.2 or earlier SDK.

**Comment by sarwadenj** [comment]
Hi @cnlohr i was using sdk 2.0.0 but after seeing
https://github.com/cnlohr/esp82xx/issues/34 
i'm using sdk 1.5.2 and it's woking.

Great wok done by you just doing some practical experiment on it. If any doubt came then i will let you know.

**Comment by sarwadenj** [comment]
Hi @cnlohr 
how should i make setup at router side.

**Comment by cnlohr** [comment]
I don't understand your question... The devices should make an AP visible, you can connect to them, and then you can configure your wifi with the web config.

**Comment by ghost** [comment]
> You're gonna have to use 1.5.2 or earlier SDK.

Early SDKs are [here](https://bbs.espressif.com/viewforum.php?f=46).
